export default {
    logoFomusic: require('../assets/logo-fomusic.png'),
    arrowBack: require('../assets/arrow-back-simple.png'),
    checkedCircle: require('../assets/check-circle-2.png'),
    eyeHidden: require('../assets/eye-hidden.png'),
    eyeOpen: require('../assets/eye-open.png'),
    facebook: require('../assets/facebook.png'),
    google: require('../assets/Google.png'),
    twitter: require('../assets/twitter.png'),
    heart: require('../assets/heart.png'),
    unHeart: require('../assets/heart1.png'),
    lock: require('../assets/lock.png'),
    logOut: require('../assets/log-out-1.png'), 
    loop: require('../assets/loop.png'),
    skipNext: require('../assets/skip-next.png'),
    skipPre: require('../assets/skip-previous.png'),
    mail: require('../assets/mail.png'),
    more: require('../assets/more-vertical.png'),
    musicNote1: require('../assets/music-note-1.png'),
    musicNote2: require('../assets/music-note-2.png'),
    notification: require('../assets/notifications.png'),
    pause: require('../assets/pause-circle.png'),
    play: require('../assets/play-circle.png'),
    playing: require('../assets/playing.png'),
    setting: require('../assets/settings.png'),
    share: require('../assets/share-1.png'),
    upload: require('../assets/upload.png'),
    userCircle: require('../assets/user-circle-dam.png'),
    userCircleBlack: require('../assets/user-circle.png')

}